name: meine_dict
description: "German vocabulary practice app with flashcards, quizzes, and more."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  flutter_tts: ^4.2.0
  web: ^1.1.0
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/german_vocabulary.json
    - lib/src/vocabeo_vocabulary.json
    - lib/src/1000_most_common_german_words.json
    - lib/src/english_german.json
